#version: '2'
#
#services:
#  app:
#    image: 'docker-spring-boot-mysql:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
###      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/SpringDataJpa
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dbquanlyhangkhong?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
##      - SPRING_DATASOURCE_USERNAME=root
##      - SPRING_DATASOURCE_PASSWORD=123456
##      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
#
#  db:
#    image: mysql
#    container_name: db
#    ports: 
#      - 3307:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=dbquanlyhangkhong
#=======================================================================================
#version: '3.6'
#
#services:
#  db:
#    image: mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: mydb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: user
#      
#    volumes:
#        - ./data:/docker-entrypoint-initdb.d
#
#  app:
#    image: mysql
#    depends_on:
#      - db
##    build:
##      context: .
#    restart: always
#    ports:
#        - 8080:8080
#    environment:
#      MYSQL_ROOT_PASSWORD: root

version: "3"
services: 
#  springboot-app:
#   # container_name: spring-app
#    image: springbooot-app
#    restart: always
#    build: .
#    ports:
#      - 8000-8999:8080 
##    environment:
##      MYSQL_HOST: mysqldb
##      MYSQL_USER: root
##      MYSQL_PASSWORD: root
##      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      - ./dockerdb/mysqldata:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: dbquanlyhangkhong
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa123
      
  springboot-app:
     depends_on:
       - mysqldb
     image: springbooot-app:runtime
     build:
       context: .
     ports:
       - "8080:8080"
