version: "3"
services: 
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      - ./dockerdb/mysqldata:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: dbquanlyhangkhong
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa123
      
  springboot-app:
     depends_on:
       - mysqldb
     image: springbooot-app:runtime
     build:
       context: .
     ports:
       - "8080:8080"
     environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/dbquanlyhangkhong?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
